return 
{
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
        ["Animate"] = "Animate"
    },
    ["Changes"] = {
         ["CloseChanges"] = {
            ["Size"] = UDim2.fromScale(2, 2)
        },
        ["OpenChanges"] = {
            ["Size"] = UDim2.fromScale(1, 1)
        }
    },
    ["Debounce"] = {
        ["Closed"] = false,
        ["Opened"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 1,
        ["ClosePrio"] = 1
    },
    ["Parent"] = "ScreenGui",
    ["AnimDuration"] = 0.5
}