return 
{
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
    },
    ["Debounce"] = {
        ["Closed"] = false,
        ["Opened"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 2,
        ["ClosePrio"] = 1
    },
    ["Changes"] = {
        ["OpenChanges"] = {
            ["Position"] = UDim2.fromScale(0.2, 0)
        },
        ["CloseChanges"] = {
            ["Position"] = UDim2.fromScale(-1, 0)
        }
    },
    ["Children"] = {

    },
    ["Parent"] = "MainMenuFrame",
    ["AnimDuration"] = 0.5
}