return 
{
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
    },
    ["Debounce"] = {
        ["Closed"] = false,
        ["Opened"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 2,
        ["ClosePrio"] = 1
    },
    ["Children"] = {

    },
    ["Parent"] = "MainMenuFrame",
    ["AnimDuration"] = 0.5
}