return 
{
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
        ["Animate"] = "Animate"
    },
    ["Changes"] = {
        ["CloseChanges"] = {
            ["Transparency"] = 1
        },
        ["OpenChanges"] = {
            ["Transparency"] = 0.6
        }
    },
    ["Debounce"] = {
        ["Closed"] = false,
        ["Opened"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 1,
        ["ClosePrio"] = 1
    },
   ["Parent"] = "ScreenGui",
   ["AnimDuration"] = 0.5
}