return 
{
    ["CloseUIs"] = {
        [1] = "MainMenuUserProfile",
        [2] = "MainMenuHeader",
        [3] = "MainMenuBackground",
        [4] = "PlayGameFrame",
        [5] = "ServersFrame",
        [6] = "SettingsFrame",
        [7] = "RoleSelectorContainer"
    },
    ["Funcs"] = {
        [1] = "Close"
    },
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
    },
       ["Debounce"] = {
        ["Status"] = "Closing"
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["TargetFolders"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 2,
        ["ClosePrio"] = 1
    },
    ["Parent"] = "PlayGameFrame",
}