return 
{
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
        ["Animate"] = "Animate"
    },
    ["Changes"] = {
        ["CloseChanges"] = {
            ["Position"] = UDim2.fromScale(-1, 0.45)
        },
        ["OpenChanges"] = {
            ["Position"] = UDim2.fromScale(0.05, 0.45)
        }
    },
    ["Debounce"] = {
        ["Closed"] = false,
        ["Opened"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 1,
        ["ClosePrio"] = 2
    },
    ["Children"] = {

    },
    ["Parent"] = "ScreenGui",
    ["AnimDuration"] = 0.5
}