return 
{
    ["CloseUIs"] = {
        [1] = "MainMenuUserProfile",
        [2] = "MainMenuHeader",
        [3] = "MainMenuBackground",
        [4] = "PlayGameFrame",
        [5] = "ServersBtnFrame",
        [6] = "SettingsBtnFrame",
        [7] = "RoleSelectorContainer",
        [8] = "Overlay"
    },
    ["OpenUIs"] = {
        [1] = "MainMenuBtn",
        -- [2] = "InGameSettingsBtn",
        -- [3] = "InGameShopBtn"
    },
    ["Funcs"] = {
        [1] = "Close",
        [2] = "Open",
        [3] = "OnPlayClicked"
    },
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
    },
    ["Debounce"] = {
        ["Closing"] = false,
        ["Opening"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["TargetFolders"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 2,
        ["ClosePrio"] = 1
    },
    ["Parent"] = "PlayGameFrame",
}