return 
{
    ["EventNames"] = {
        ["Closed"] = "Closed",
        ["Opened"] = "Opened",
    },
    ["Debounce"] = {
        ["Closed"] = false,
        ["Opened"] = false
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Prios"] = {
        ["OpenPrio"] = 2,
        ["ClosePrio"] = 1
    },
    ["State"] = "Selected",
    ["Parent"] = "RoleSelectorContainer",
    ["AnimDuration"] = 0.5,

    -- Functionalities and responsibilites
    ["Direction"] = -1,
    ["GameFuncs"] = {
        ["ArrowSelectorClicked"] = "ArrowSelectorClicked",
    },
}