return {
    ["Status"] = {
        ["IsRunning"] = false,
        ["IsWalking"] = true,
        ["IsCrouching"] = false,
        ["IsStanding"] = true,
        ["Destroyed"] = false,
        ["Destroying"] = false
    },
    ["EventNames"] = {
        [1] = "Destroyed",
    },
    ["Events"] = {

    },
    ["AnimationIds"] = {
        ["RunAnim"] = nil -- ID HERE 
    },
    ["FuncNames"] = {
        [1] = "DestroyUponDeath"
    },
}