return {

   ["OpenPrompt"] = {
        ["OpenUIs"] = {
            [1] = "Prompt",
            [2] = "Prompt1",
            [3] = "Prompt2"
        },
        ["Funcs"] = {
            [1] = "Open"
        },
        ["EventNames"] = {
            ["Opened"] = "Opened"
        },
        ["Events"] = {

        },
        ["Connections"] = {

        },
        ["TargetFolders"] = {

        },
        ["Prios"] = {
            
        },
        ["Parent"] = "ScreenGui"
   }, 
   
   ["PromptFrame"] = {
        ["EventNames"] = {
            ["Opened"] = "Opened"
        },
        ["Events"] = {

        },
        ["Prios"] = {
            ["OpenPrio"] = 1,
            ["ClosePrio"] = 2
        },
        ["Parent"] = "ScreenGui"
   }

}