return {
    ["EventNames"] = {
        
    },
    ["Events"] = {

    },
    ["Connections"] = {

    },
    ["Status"] = {
        ["GameState"] = "InMainMenu"
    },
    ["FuncNames"] = {
        [1] = "CharacterDestroyed",
        [2] = "OnPlayGameClicked",
        [3] = "OnGameStateChanged",
        [4] = "RoleSelectionChanged"
    },
    ["SpawnPoint"] =  CFrame.new(Vector3.new(5, 15, 0))
}